-- schema.sql
-- Create Tables for Class Test Planner
-- Assumes connection as CLASS_TEST_PLANNER_DB_1 or similar user

-- 1. STUDENTS Table
CREATE TABLE STUDENTS (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. COURSES Table
CREATE TABLE COURSES (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    course_code VARCHAR2(20) NOT NULL,
    course_name VARCHAR2(200) NOT NULL,
    credits NUMBER DEFAULT 3 NOT NULL,
    target_total_marks NUMBER DEFAULT 50, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_student
        FOREIGN KEY (student_id)
        REFERENCES STUDENTS(student_id)
        ON DELETE CASCADE
);

-- 3. CLASS_TESTS Table
CREATE TABLE CLASS_TESTS (
    ct_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id NUMBER NOT NULL,
    test_number NUMBER NOT NULL, -- e.g., 1, 2, 3, 4
    marks_obtained NUMBER, -- Nullable until taken
    total_marks NUMBER DEFAULT 20 NOT NULL,
    CONSTRAINT fk_course
        FOREIGN KEY (course_id)
        REFERENCES COURSES(course_id)
        ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX idx_course_student ON COURSES(student_id);
CREATE INDEX idx_ct_course ON CLASS_TESTS(course_id);

-- 4. TRIGGER: Auto-create Class Tests when a Course is created
CREATE OR REPLACE TRIGGER trg_create_class_tests
AFTER INSERT ON COURSES
FOR EACH ROW
DECLARE
    v_num_tests NUMBER;
BEGIN
    v_num_tests := :new.credits + 1;
    
    FOR i IN 1 .. v_num_tests LOOP
        INSERT INTO CLASS_TESTS (course_id, test_number, marks_obtained, total_marks)
        VALUES (:new.course_id, i, NULL, 20);
    END LOOP;
END;
/
